### ISSUE TITLE
Logging level setting + bug in level handling

### ISSUE THREAD

**Issue by ux-engineer** [rcrowe/Raven#1]
Hi,

Could you please implement logging levels. What level and up should get logged. Now I'm getting them all

And there seems to be a bug that each Log::info() is on the level "error" in Sentry's UI...

**Comment by rcrowe** [comment]
I had left this out on the initial release, it's annoying me as well :)

I'll take a look at the bug and implement logging levels for the next release.

**Comment by ux-engineer** [comment]
Ok thanks!

**Comment by rcrowe** [comment]
I'm in the process of fixing this in the [feature/0.2.0](https://github.com/rcrowe/Raven/tree/release/0.2.0) branch

**Comment by rcrowe** [comment]
So this is all done in 0.2.0 which I'll release shortly

**Comment by ux-engineer** [comment]
Great to hear, thanks! :+1:
