### ISSUE TITLE
Adding extra information from Laravel provider

### ISSUE THREAD

**Issue by srtfisher** [rcrowe/Raven#2]
I think it would a great addition to have the ability to add extra information to pass to Sentry from the Laravel provider. I would love to pass in user info, server name, environment etc.

Unless this is currently possible... Seems to be possible with the Raven PHP client.

**Comment by rcrowe** [comment]
This should already be possible, the client extends the default Raven client.

When time permits I want to add in better support for collecting automatically from Laravel.

**Comment by srtfisher** [comment]
Thank you for building this, too. Made my life easier to add Sentry support to Laravel.

**Comment by srtfisher** [comment]
Would also be great to have the Log Level feature that you had for your laravel-sentry package put back into it.

**Comment by rcrowe** [comment]
Yeah working on that one. Someone raised that the other day.

Happy to accept pull requests :)

**Comment by ux-engineer** [comment]
@rcrowe Better be working on that one! :D :+1: Practically I cannot use this package nor Sentry (unless installing the old package) as Sentry will soon be full of info level loggings as errors!

**Comment by ux-engineer** [comment]
:+1: For automatic details!

**Comment by rcrowe** [comment]
I'll have this all fixed in the [feature/0.2.0](https://github.com/rcrowe/Raven/tree/release/0.2.0) branch which should be out shortly.

**Comment by rcrowe** [comment]
So log levels are now support.

There are 3 new helper functions:
- `Log::setUser()` - Set the logged in user
- `Log::removeUser()` - Remove the user from logs
- `Log::exception()` - Wrapper function to make things nicer when logging exceptions.

If you need to set any custom extra context/tags etc you have access to the Raven client, like so:

``` php
App::make('log.sentry')->extra_context(...);
```

You can also pass extra context through the log methods which will be passed on to Sentry:

``` php
Log::error('message goes here', [
    'foo' => 'bar'
]);
```

Overall, there is much better integration with Sentry now. Let me know if I can add anything else. Few more tests to write, then I'll merge and tag 0.2.0.

**Comment by rcrowe** [comment]
Think I'm going to remove `Log::exception()` as there's complexities around (log level) that just aren't needed.

Instead I'll patch the log methods to react to receiving an `Exception` object passed in.

**Comment by rcrowe** [comment]
Removed `Log::exception`, now just use `Log::error($exception, $context = array())`

**Comment by jbrooksuk** [comment]
With `Log::setUser`, is this something I can call in `start.php` with `Log::setUser(Auth::user())`?
