### ISSUE TITLE
Tagging releases

### ISSUE THREAD

**Issue by johnnye** [rcrowe/Raven#3]
Can we have a tagged release please, cleaner of production environments. 

Cheers

**Comment by rcrowe** [comment]
I pushed this for you to test out before tagging haha :) I jest. 

I'll tag a release now. I actually have a load of issues fixed in our work fork, so I'll get that up as soon as I can.

**Comment by rcrowe** [comment]
Done!

**Comment by johnnye** [comment]
ooops. I'll be working on it tomorrow so will test then. Honest gov.

**Comment by rcrowe** [comment]
I'll have the [feature/0.2.0](https://github.com/rcrowe/Raven/tree/release/0.2.0) branch out by tomorrow. A lot of it's been rewritten, so if you can test that, that would be grand :)
