### ISSUE TITLE
Method [callMonolog] does not exist

### ISSUE THREAD

**Issue by ux-engineer** [rcrowe/Raven#5]
I'm getting?

Error in exception handler: Method [callMonolog] does not exist. in .... \vendor\rcrowe\raven\src\Provider\Laravel\Log.php:119

**Comment by rcrowe** [comment]
Strange, `rcrowe\Raven\Provider\Laravel\Log` should extend `Illuminate\Log\Writer` which has the [callMonolog](https://github.com/laravel/framework/blob/master/src/Illuminate/Log/Writer.php#L65) method.

How are you calling `Log`?

**Comment by ux-engineer** [comment]
Log::info, Log::debug, Log::error ...

**Comment by rcrowe** [comment]
Unable to replicate & no one else has reported this in the many months since it was reported.

Once we get a case where I can replicate it, I'll reopen the ticket.

**Comment by threesquared** [comment]
It seems this method is missing in the 4.0 version of `Illuminate\Log\Writer`

https://github.com/laravel/framework/blob/4.0/src/Illuminate/Log/Writer.php
