### ISSUE TITLE
Upgrading to Guzzle 3.8.*

### ISSUE THREAD

**Issue by trampish** [rcrowe/Raven#6]
Hi there, is there any chance we could upgrade the composer.json requirements to guzzle/guzzle 3.8.\* ? I'm running into some conflicts with other packages requiring the newer Guzzle library. Thanks!

**Comment by rcrowe** [comment]
Yep, I'll sort that out.

0.2.x is using 3.8.x if you want to venture into a work in progress.

**Comment by rcrowe** [comment]
0.2.0 now runs `~4.1.0` which is pretty close to being released

**Comment by trampish** [comment]
Awesome, thanks!
