### ISSUE TITLE
Do not run on Queue

### ISSUE THREAD

**Issue by jbrooksuk** [rcrowe/Raven#8]
Is it possible to stop Raven from sending logs via the queue, when `debug = TRUE`? We're not too fussed about it logging errors slowly when developing.

**Comment by rcrowe** [comment]
You can set your `queue.php` config file driver as `sync` to process the queue straight away.

**Comment by jbrooksuk** [comment]
That's not quite what I'm after. Can I override the `dsn` configuration in my local environment, so that Raven won't be running?

**Comment by rcrowe** [comment]
Sorry that I miss understood.

Hopefully this is what you are after -> [Cascading Configuration Files](http://laravel.com/docs/packages)

So once you have published Ravens config file you can override the `enabled` config option for your local environment.

**Comment by rcrowe** [comment]
When you publish the Raven config it will now stop logging on the `local` environment

**Comment by jbrooksuk** [comment]
Awesome!
