### ISSUE TITLE
Log user

### ISSUE THREAD

**Issue by jbrooksuk** [rcrowe/Raven#9]
In Sentry I notice that the User information is blank. Is it possible to send the `Auth::user()` object with the log, so that we're able to see which user had the error?

**Comment by stayallive** [comment]
Try this:

```
if (Auth::check()) {
    Log::setUser([
        'id' => Auth::user()->id
    ]);
}
```

It wants an array so you could also use `Auth::user()->toArray()` but I use this because the ID is the only thing important to me in the logs.

**Comment by rcrowe** [comment]
Thanks @Stayallive 

Next task is to get some docs together then I can tag / release. Any feedback on 0.2.0 so far would be great before I tag.

**Comment by rcrowe** [comment]
Just a thought, but to me `Log::setUser` doesn't really belong. It seems better to me to do `Sentry::setUser(...)`.

Going down that line will allow us to wrap and give a nicer interface to the raven client.

**Comment by jbrooksuk** [comment]
`Sentry::setUser()` makes more sense, it's self-contained and doesn't muddy up the `Log` API. :+1: from me.

**Comment by rcrowe** [comment]
So this is done. You just need to add the following facade to your `app.php` config file:

``` php
'Sentry' => 'rcrowe\Raven\Provider\Laravel\Facade\Sentry'
```

The facade exposes `setUser` & `removeUser` but also allows you to call any method on `rcrowe\Raven\Client`

**Comment by stayallive** [comment]
Is this a bc break? Or is `Log::setUser()` still possible?

**Comment by rcrowe** [comment]
As 0.2.0 hasn't been released it will be yes.

**Comment by stayallive** [comment]
No worries, just asking FMI so I know when I update ;)
